import { Link } from 'react-router-dom'
import { Brain, ArrowLeft } from 'lucide-react'
import { BrandLogo } from '@/components/shared'

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-bg-primary">
      <nav className="sticky top-0 z-50 border-b border-border bg-bg-card/80 backdrop-blur-xl">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-primary to-accent">
              <Brain className="h-5 w-5 text-white" />
            </div>
            <BrandLogo className="text-lg" />
          </Link>
          <Link to="/" className="flex items-center gap-2 text-sm text-text-secondary hover:text-text-primary transition-colors">
            <ArrowLeft className="h-4 w-4" />
            Back to home
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-heading font-extrabold text-text-primary mb-2">Terms of Service</h1>
        <p className="text-sm text-text-tertiary mb-10">Last updated: July 31, 2026</p>

        <div className="prose-dark space-y-8 text-text-secondary leading-relaxed">
          <section>
            <h2 className="text-xl font-heading font-bold text-text-primary mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using AssessAI (&quot;the Platform&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.</p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-text-primary mb-3">2. Description of Service</h2>
            <p>AssessAI is an AI-powered assessment platform that enables users to create, manage, take, and analyze assessments. Features include AI question generation, real-time proctoring, coding assessments, and analytics dashboards.</p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-text-primary mb-3">3. User Accounts</h2>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>You must provide accurate and complete information when creating an account.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must notify us immediately of any unauthorized use of your account.</li>
              <li>You must be at least 13 years old to use the Platform.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-text-primary mb-3">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Cheat or attempt to circumvent proctoring mechanisms during assessments.</li>
              <li>Share assessment content with unauthorized parties.</li>
              <li>Use the Platform for any illegal or unauthorized purpose.</li>
              <li>Attempt to gain unauthorized access to other accounts or systems.</li>
              <li>Interfere with or disrupt the Platform&apos;s infrastructure.</li>
              <li>Use automated tools to interact with the Platform without authorization.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-text-primary mb-3">5. Assessment Integrity</h2>
            <p>When taking proctored assessments, you acknowledge that:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Your webcam, screen, and audio may be monitored during the assessment.</li>
              <li>Tab switches and suspicious behavior will be logged and flagged.</li>
              <li>Violation of assessment integrity rules may result in account suspension.</li>
              <li>Assessment creators define their own proctoring strictness levels.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-text-primary mb-3">6. Intellectual Property</h2>
            <p>The Platform, including its design, code, and features, is owned by AssessAI and protected by intellectual property laws. User-created content (questions, assessments) remains the property of the creator. We do not claim ownership over user-generated content.</p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-text-primary mb-3">7. AI-Generated Content</h2>
            <p>Questions and content generated by AI features are provided as suggestions. Users are responsible for reviewing and validating AI-generated content before use. We do not guarantee the accuracy or completeness of AI-generated material.</p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-text-primary mb-3">8. Limitation of Liability</h2>
            <p>The Platform is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from the use of the Platform, including but not limited to assessment outcomes, data loss, or service interruptions.</p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-text-primary mb-3">9. Termination</h2>
            <p>We reserve the right to suspend or terminate your account at our discretion, including for violations of these Terms. You may also delete your account at any time from the settings page.</p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-text-primary mb-3">10. Changes to Terms</h2>
            <p>We may update these Terms from time to time. Continued use of the Platform after changes constitutes acceptance of the new Terms. We will notify users of significant changes.</p>
          </section>

          <section>
            <h2 className="text-xl font-heading font-bold text-text-primary mb-3">11. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="mailto:ravipratap.gusknp2022@gmail.com" className="text-primary hover:underline">ravipratap.gusknp2022@gmail.com</a>.</p>
          </section>
        </div>
      </main>
    </div>
  )
}
