import express from 'express'

const router = express.Router()

const termsHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Terms of Service - AssessAI</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', system-ui, -apple-system, sans-serif; background: #09090B; color: #FAFAFA; line-height: 1.7; }
    .container { max-width: 720px; margin: 0 auto; padding: 40px 24px 80px; }
    nav { border-bottom: 1px solid #27272A; padding: 16px 24px; }
    nav a { color: #A1A1AA; text-decoration: none; font-size: 14px; }
    nav a:hover { color: #FAFAFA; }
    h1 { font-size: 32px; font-weight: 800; margin-bottom: 8px; }
    .date { color: #71717A; font-size: 13px; margin-bottom: 40px; }
    h2 { font-size: 20px; font-weight: 700; color: #FAFAFA; margin: 32px 0 12px; }
    p { color: #A1A1AA; margin-bottom: 12px; }
    ul { color: #A1A1AA; padding-left: 24px; margin-bottom: 12px; }
    li { margin-bottom: 6px; }
    strong { color: #FAFAFA; }
    a { color: #6366F1; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <nav><a href="/">← AssessAI</a></nav>
  <div class="container">
    <h1>Terms of Service</h1>
    <p class="date">Last updated: July 31, 2026</p>

    <h2>1. Acceptance of Terms</h2>
    <p>By accessing or using AssessAI ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.</p>

    <h2>2. Description of Service</h2>
    <p>AssessAI is an AI-powered assessment platform that enables users to create, manage, take, and analyze assessments. Features include AI question generation, real-time proctoring, coding assessments, and analytics dashboards.</p>

    <h2>3. User Accounts</h2>
    <ul>
      <li>You must provide accurate and complete information when creating an account.</li>
      <li>You are responsible for maintaining the security of your account credentials.</li>
      <li>You must notify us immediately of any unauthorized use of your account.</li>
      <li>You must be at least 13 years old to use the Platform.</li>
    </ul>

    <h2>4. Acceptable Use</h2>
    <p>You agree not to:</p>
    <ul>
      <li>Cheat or attempt to circumvent proctoring mechanisms during assessments.</li>
      <li>Share assessment content with unauthorized parties.</li>
      <li>Use the Platform for any illegal or unauthorized purpose.</li>
      <li>Attempt to gain unauthorized access to other accounts or systems.</li>
      <li>Interfere with or disrupt the Platform's infrastructure.</li>
      <li>Use automated tools to interact with the Platform without authorization.</li>
    </ul>

    <h2>5. Assessment Integrity</h2>
    <p>When taking proctored assessments, you acknowledge that:</p>
    <ul>
      <li>Your webcam, screen, and audio may be monitored during the assessment.</li>
      <li>Tab switches and suspicious behavior will be logged and flagged.</li>
      <li>Violation of assessment integrity rules may result in account suspension.</li>
    </ul>

    <h2>6. Intellectual Property</h2>
    <p>The Platform, including its design, code, and features, is owned by AssessAI and protected by intellectual property laws. User-created content remains the property of the creator.</p>

    <h2>7. AI-Generated Content</h2>
    <p>Questions and content generated by AI features are provided as suggestions. Users are responsible for reviewing and validating AI-generated content before use.</p>

    <h2>8. Limitation of Liability</h2>
    <p>The Platform is provided "as is" without warranties of any kind. We are not liable for any damages arising from the use of the Platform.</p>

    <h2>9. Termination</h2>
    <p>We reserve the right to suspend or terminate your account at our discretion, including for violations of these Terms. You may also delete your account at any time from the settings page.</p>

    <h2>10. Changes to Terms</h2>
    <p>We may update these Terms from time to time. Continued use of the Platform after changes constitutes acceptance of the new Terms.</p>

    <h2>11. Contact</h2>
    <p>For questions about these Terms, contact us at <a href="mailto:ravipratap.gusknp2022@gmail.com">ravipratap.gusknp2022@gmail.com</a>.</p>
  </div>
</body>
</html>`

router.get('/terms', (_, res) => {
  res.set('Content-Type', 'text/html')
  res.send(termsHTML)
})

export default router
